### ISSUE TITLE
Tournament location data

### ISSUE THREAD

**Issue by fluid-movement** [freestyle-players-association/fpa-app#5]
# How should we handle tournament location?

One way is a naive text input: let the creator put in "Berlin", or "Warsaw".
Another would be to use an API like the Google Places API. User searches for a location, we store the response data, for example "Berlin Tempelhof", we store the place_id, latitude and longitude, address, etc.

## Things to think about:

- what if events have several locations? 
- what if the location is not known exactly? Then the simple text input would be easier.

## Feature ideas:

Use the google places API to mark several locations on a map. Creator of the tournament could create as many markers as they want, then they can link to these markers in a text.

## MVP suggestion
Use a text box in which the creator can input a city. We can either use Google Places to verify the city, or just let them put in whatever.
Google Places integration could be a V2 feature.

**Comment by zzZCodeZzz** [comment]
In order to solve the issue with multiple locations I would introduce the schedule-relation (one-to-many).

Each schedule entry would have at least a time, name, description and location. The location should consist of lat, long and address, of which you can construct a link for google maps again.

To get the lat, long and address I would  use the palces api + geocoding api of google, to make shure that a valid address/coordinates are picked.

If the location is not known yet, we can make the fields for location optional, or also use the places api + geocoding, since you can also use this for the usecase of just having a city as location, when location is not known yet.
